"""Tax regime configurations for all countries."""

from .bulgaria import BULGARIA_FREELANCER
from .czechia import CZECHIA_FREELANCER, CZECHIA_SALARIED
from .france import FRANCE_SALARIED
from .germany import GERMANY_SALARIED
from .israel import ISRAEL_SALARIED
from .portugal import PORTUGAL_FREELANCER, PORTUGAL_SALARIED
from .romania import ROMANIA_FREELANCER_MICRO
from .spain import BARCELONA_SALARIED, MADRID_SALARIED, VALENCIA_SALARIED

__all__ = [
    "GERMANY_SALARIED",
    "CZECHIA_SALARIED",
    "CZECHIA_FREELANCER",
    "ISRAEL_SALARIED",
    "FRANCE_SALARIED",
    "MADRID_SALARIED",
    "BARCELONA_SALARIED",
    "VALENCIA_SALARIED",
    "ROMANIA_FREELANCER_MICRO",
    "BULGARIA_FREELANCER",
    "PORTUGAL_SALARIED",
    "PORTUGAL_FREELANCER",
]
